name: Test LemLib Without the File Hash
on:
  workflow_call:

jobs:
  Test_LemLib_Without_Adding_the_Commit_Hash:
    name: "Testing LemLib Without Adding the Commit Hash"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LemLib/LemLib
          ref: stable

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload No Hash
        id: test
        uses: ./action/
        with:
          no_commit_hash: true

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.name }}
          path: "template/*"

      - name: Add Artifact to Job Summary
        run: 'echo "### ðŸ“¦ Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'
